import type { ICore, IUI, NodeWorkerFnType } from "../Interfaces";
declare global {
    interface Window {
        locoVmWorker: NodeWorkerFnType;
    }
}
export declare class UI implements IUI {
    private core?;
    private vmMain?;
    private basicCm?;
    private compiledCm?;
    private compiledMessages;
    private initialUserAction;
    private readonly fnOnKeyPressHandler;
    private readonly fnOnClickHandler;
    private readonly fnOnUserKeyClickHandler;
    private speechSynthesisUtterance?;
    private locoVmWorkerName;
    private pendingInputResolver?;
    constructor();
    private isCodeMirrorSetValue;
    private debounce;
    private static asyncDelay;
    private getCore;
    private getVmMain;
    private getBasicCm;
    private getCompiledCm;
    private cancelSpeech;
    private toggleElementHidden;
    private getElementHidden;
    private setElementHidden;
    private closeAllPopoversExcept;
    private togglePopoverHidden;
    private setButtonOrSelectDisabled;
    private fnLoadScriptOrStyle;
    private loadScript;
    getCurrentDataKey(): string;
    private scrollToBottom;
    addOutputText: (str: string, needCls?: boolean, hasGraphics?: boolean) => void;
    private onUserKeyClick;
    private onSetUiKeys;
    private waitForVoices;
    private waitForUserInteraction;
    private showConsoleInput;
    private logVoiceDebugInfo;
    private getSpeechSynthesisUtterance;
    private onGeolocation;
    private onSpeak;
    private updateConfigParameter;
    private hasCompiledError;
    private updateButtonStates;
    private beforeExecute;
    private afterExecute;
    private onExecuteButtonClick;
    private onCompiledTextChange;
    private onCompileButtonClick;
    private onEnterButtonClick;
    private onAutoCompileInputChange;
    private onAutoExecuteInputChange;
    private onShowOutputInputChange;
    private onShowBasicInputChange;
    private onShowCompiledInputChange;
    private clickStartSpeechButton;
    private onStopButtonClick;
    private onResetButtonClick;
    private onOutputOptionsButtonClick;
    private onConvertButtonClick;
    private onBasicSearchButtonClick;
    private onBasicReplaceButtonClick;
    private onBasicReplaceAllButtonClick;
    private onBasicSearchNextButtonClick;
    private onBasicSearchPrevButtonClick;
    private onBasicSearchInputChange;
    private onBasicSearchInputKeydown;
    private onFullscreenButtonClick;
    private onFrameInputChange;
    private static addLabels;
    private static removeUnusedLabels;
    private onLabelAddButtonClick;
    private onLabelRemoveButtonClick;
    private onBasicTextChange;
    private getExampleScript;
    private onExampleSelectChange;
    private setExampleSelectOptions;
    private getExampleMap;
    private onDatabaseSelectChange;
    private setDatabaseSelectOptions;
    private onHelpButtonClick;
    private static fnDownloadBlob;
    private getExampleName;
    private onExportSvgButtonClick;
    private onStandaloneButtonClick;
    private putKeysInBuffer;
    private onOutputTextKeydown;
    private getClickedKey;
    private onOutputTextClick;
    private fnDecodeUri;
    private parseUri;
    private initializeEditor;
    private syncInputState;
    private getLocoVmWorker;
    createWebWorker(): Promise<Worker>;
    private createMessageHandlerCallbacks;
    onWindowLoadContinue(core: ICore, locoVmWorkerName: string): void;
}
//# sourceMappingURL=UI.d.ts.map