import type { IVmRsxApi, SnippetDataType } from "./Interfaces";
export declare class BasicVmCore implements IVmRsxApi {
    private readonly penColors;
    private readonly paperColors;
    private output;
    private currPaper;
    private currPen;
    private hasPaperChanged;
    private hasPenChanged;
    private currMode;
    private currPos;
    private currVpos;
    private currZone;
    private readonly graphicsBuffer;
    private readonly graphicsPathBuffer;
    private currGraphicsPen;
    private originX;
    private originY;
    private graphicsX;
    private graphicsY;
    private readonly colorsForPens;
    private backgroundColor;
    private isTag;
    private snippetData;
    private rsxHandler;
    private static readonly cpcColors;
    private readonly defaultColorsForPens;
    constructor(penColors: string[], paperColors: string[]);
    static getCpcColors(): string[];
    private static deleteAllItems;
    reset(): void;
    cls(): void;
    mode(num: number): void;
    drawMovePlot(type: string, x: number, y: number): void;
    getGraphicsPen(): number;
    getRgbColorStringForPen(pen: number): string;
    private flushGraphicsPath;
    addGraphicsElement(element: string): void;
    static getTagInSvg(content: string, strokeWidth: string, backgroundColor: string): string;
    flushGraphics(): string;
    flushText(): string;
    graphicsPen(num: number): void;
    ink(num: number, col: number): void;
    origin(x: number, y: number): void;
    paper(n: number): void;
    pen(n: number): void;
    pos(): number;
    private printGraphicsText;
    private printText;
    print(...args: string[]): void;
    setOnSpeak(fnOnSpeak: (text: string, pitch: number) => Promise<void>): void;
    rsx(cmd: string, args: (number | string)[]): Promise<(number | string)[]>;
    tag(active: boolean): void;
    vpos(): number;
    xpos(): number;
    ypos(): number;
    zone(num: number): void;
    getSnippetData(): SnippetDataType;
    getOutput(): string;
}
//# sourceMappingURL=BasicVmCore.d.ts.map