import type { TimerMapType } from "./Interfaces";
export declare class BasicVmCore {
    private readonly penColors;
    private readonly paperColors;
    private output;
    private currPaper;
    private currPen;
    private currMode;
    private readonly graphicsBuffer;
    private readonly graphicsPathBuffer;
    private currGraphicsPen;
    private originX;
    private originY;
    private graphicsX;
    private graphicsY;
    private readonly colorsForPens;
    private backgroundColor;
    private isTag;
    private timerMap;
    private pitch;
    private fnOnSpeak;
    private static readonly cpcColors;
    private readonly defaultColorsForPens;
    constructor(penColors: string[], paperColors: string[]);
    static getCpcColors(): string[];
    private reset;
    cls(): void;
    drawMovePlot(type: string, x: number, y: number): void;
    private flushGraphicsPath;
    getFlushedGraphics(): string;
    graphicsPen(num: number): void;
    ink(num: number, col: number): void;
    mode(num: number): void;
    origin(x: number, y: number): void;
    paper(n: number): void;
    pen(n: number): void;
    private printGraphicsText;
    print(...args: string[]): void;
    setOnSpeak(fnOnSpeak: (text: string, pitch: number) => Promise<void>): void;
    private getStrokeAndFillStr;
    private rsxArc;
    private rsxCircle;
    private rsxDate;
    private rsxEllipse;
    private rsxRect;
    private rsxPitch;
    private rsxSay;
    private rsxTime;
    private rsxMap;
    rsx(cmd: string, args: (number | string)[]): Promise<(number | string)[]>;
    tag(active: boolean): void;
    xpos(): number;
    ypos(): number;
    getEscape(): boolean;
    getTimerMap(): TimerMapType;
    getOutput(): string;
    setOutput(str: string): void;
}
//# sourceMappingURL=BasicVmCore.d.ts.map