import type { DefinedLabelEntryType, UsedLabelEntryType } from "./Interfaces";
type VariableScopesEntryType = Record<string, number>;
export type VariableScopesType = Record<string, VariableScopesEntryType>;
export declare class SemanticsHelper {
    private lineIndex;
    private indent;
    private readonly compileMessages;
    private readonly variables;
    private readonly variableScopes;
    private readonly varLetterTypes;
    private currentFunction;
    private readonly definedLabels;
    private readonly usedLabels;
    private readonly dataList;
    private dataIndex;
    private readonly restoreMap;
    private static readonly reJsKeyword;
    private readonly instrMap;
    private isDeg;
    private defContextStatus;
    private readonly defContextVars;
    addCompileMessage(message: string): void;
    getCompileMessages(): string[];
    getDeg(): boolean;
    setDeg(isDeg: boolean): void;
    addIndent(num: number): number;
    setIndent(indent: number): void;
    getIndent(): number;
    getIndentStr(): string;
    addDataIndex(count: number): number;
    getDataIndex(): number;
    addDefinedLabel(label: string, line: number): void;
    getDefinedLabels(): DefinedLabelEntryType[];
    addUsedLabel(label: string, type: string): void;
    getUsedLabels(): Record<string, Record<string, UsedLabelEntryType>>;
    getInstrMap(): Record<string, number>;
    addInstr(name: string): number;
    getVariables(): string[];
    private createVariableOrCount;
    getVariable(name: string): string;
    getVariableScopes(): VariableScopesType;
    setCurrentFunction(label: string): void;
    setDefContextStatus(status: string): void;
    setVarLetterTypes(letters: string[], type: string): void;
    getVarType(name: string): string;
    private static deleteAllItems;
    incrementLineIndex(): number;
    getRestoreMap(): Record<string, number>;
    addRestoreLabel(label: string): void;
    getDataList(): (string | number)[];
    resetParser(): void;
}
export {};
//# sourceMappingURL=SemanticsHelper.d.ts.map