import type { ActionDict } from "ohm-js";
import type { DefinedLabelEntryType, GosubLabelEntryType, ISemanticsHelper } from "./Interfaces";
export declare class Semantics implements ISemanticsHelper {
    private lineIndex;
    private indent;
    private indentAdd;
    private readonly variables;
    private readonly definedLabels;
    private readonly gosubLabels;
    private readonly dataList;
    private dataIndex;
    private readonly restoreMap;
    private static readonly reJsKeyword;
    private readonly instrMap;
    private isDeg;
    private isDefContext;
    getDeg(): boolean;
    setDeg(isDeg: boolean): void;
    addIndent(num: number): number;
    setIndent(indent: number): void;
    getIndent(): number;
    getIndentStr(): string;
    applyNextIndent(): void;
    nextIndentAdd(num: number): void;
    addDataIndex(count: number): number;
    getDataIndex(): number;
    addDefinedLabel(label: string, line: number): void;
    getDefinedLabels(): DefinedLabelEntryType[];
    addGosubLabel(label: string): void;
    getGosubLabels(): Record<string, GosubLabelEntryType>;
    getInstrMap(): Record<string, number>;
    addInstr(name: string): number;
    getVariables(): string[];
    getVariable(name: string): string;
    setDefContext(isDef: boolean): void;
    private static deleteAllItems;
    incrementLineIndex(): number;
    getRestoreMap(): Record<string, number>;
    addRestoreLabel(label: string): void;
    getDataList(): (string | number)[];
    resetParser(): void;
    getSemantics(): ActionDict<string>;
}
//# sourceMappingURL=Semantics.d.ts.map